### ISSUE TITLE
Disable gutter and horizontal scroll

### ISSUE THREAD

**Issue by hongquan** [kullna/editor#28]
[x] I would be willing to contribute this feature to the project if given guidance and support.

I want to use Kullna Editor to edit Markdown document. But the current behavior is not very suitable:
- It always renders Gutter. For Markdown document, gutter is not needed.
- Each Markdown line is corresponding to a paragraph, so it is often very long. Kullna always create horizontal scroll, so it is difficult to read the paragraph.

**Comment by StevenEWright** [comment]
Just added support for wrapping:

https://github.com/kullna/editor/pull/26

If the gutter isn't disabled by not passing a gutter object in the options, i will fix that today. And make the documentation on how to do it clearer

**Comment by StevenEWright** [comment]
Hey @hongquan! 

Thanks for the report. Please check https://editor.kullna.org/demo.html 

I've added a demo with no gutter.

When you call `createEditor(element, options);` simply omit any `gutter` option and there will be no gutter - or, set the width to `0px`.

Also, I've set the `wrapsText` to `true` on that demo, so it's basically your use case.

Thanks again 👍
